
name: Infrastructure Update


on:
  workflow_dispatch:

jobs:
  plan_changes:    
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Run terraform plan
        run: |
          terraform init
          terraform plan
