
name: Infrastructure Update


on:
  workflow_dispatch:

jobs:
  plan_changes:
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Run terraform plan
        run: |
          terraform init
          terraform plan
