
name: Infrastructure Update


on:
  workflow_dispatch:

jobs:
  plan_changes:
    name: Plan changes (Production)
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Run terraform plan
        run: |
          terraform init
          terraform plan -out initial.tfplan
      - uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: initial.tfplan     
          
  apply_changes_prod:
    name: Apply changes (Production)
    environment: production
    needs: plan_changes
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: tfplan
      - name: Run terraform apply
        run: |
          terraform apply initial.tfplan 
